server:
  port: 8080

spring:
  application:
    name: conversation
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5433/conversation_db
  jpa:
    database: postgresql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
